add season selection
AnthonyMichaelTDM/DRG-Save-Editor pull request #64
Opened 2024-07-07 15:59 UTC by wahlp

resolves #63

adds a new dropdown and label, to let users view and edit the seasonal xp and scrip for all seasons

2024-07-07 21:30 UTC, AnthonyMichaelTDM commented
I’ll merge once some other people can confirm it works as intended, also, can you provide a screenshot of the new ui?

2024-07-08 11:05 UTC, wahlp commented
![image](https://github.com/AnthonyMichaelTDM/DRG-Save-Editor/assets/25950922/79c82e3c-564e-4d53-82d6-834e12fbbe2b)

the new dropdown is below all the promotion dropdowns

2024-07-08 13:01 UTC, wahlp commented
found a possible scenario of it not working.

there exists the possibility of some seasonal data not being present (eg. player did not play season 4, so no relevant data was generated for season 4). if this is the case, the whole section of ui elements for seasonal content, including the dropdown, will become locked.

will add more commits to fix this.

2024-07-10 11:09 UTC, simon-wg requested changes
All in all i think it looks good! Works well on my machine, however I would like to request some changes in order to better follow good coding practices.

2024-07-10 11:09 UTC, simon-wg commented on src/main/python/main.py
> +            seasons_present.append(season_num)
I would replace with this
```
try:
    stats["season-changes"][season_num] = get_season_data(save_data, season_guid)        
except:
    break
else: seasons_present.append(season_num)
```

2024-07-10 12:23 UTC, wahlp commented on src/main/python/main.py
> +            seasons_present.append(season_num)
i would go with

```py
else:
    seasons_present.append(season_num)
```

rather than having them on the same line, but i agree with the rest of the changes

2024-07-10 17:46 UTC, simon-wg approved these changes
lgtm!

2024-07-10 23:16 UTC, AnthonyMichaelTDM commented
Sweet, thanks for the work @wahlp and thank you @simon-wg for the review.

2024-07-10 23:16 UTC, merged